Apply shfmt formatting

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,16 +1,16 @@
 #!/usr/bin/env bash
 
 if [ -f "${1:?}/pom.xml" ] ||
-    [ -f "${1:?}/pom.atom" ] ||
-    [ -f "${1:?}/pom.clj" ] ||
-    [ -f "${1:?}/pom.groovy" ] ||
-    [ -f "${1:?}/pom.rb" ] ||
-    [ -f "${1:?}/pom.scala" ] ||
-    [ -f "${1:?}/pom.yaml" ] ||
-    [ -f "${1:?}/pom.yml" ] ; then
-  echo "Java"
-  exit 0
+	[ -f "${1:?}/pom.atom" ] ||
+	[ -f "${1:?}/pom.clj" ] ||
+	[ -f "${1:?}/pom.groovy" ] ||
+	[ -f "${1:?}/pom.rb" ] ||
+	[ -f "${1:?}/pom.scala" ] ||
+	[ -f "${1:?}/pom.yaml" ] ||
+	[ -f "${1:?}/pom.yml" ]; then
+	echo "Java"
+	exit 0
 else
-  (>&2 echo "Could not find a pom.xml file! Please check that it exists and is committed to Git.")
-  exit 1
+	(>&2 echo "Could not find a pom.xml file! Please check that it exists and is committed to Git.")
+	exit 1
 fi
