Format source with shfmt

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,24 +1,24 @@
 #!/usr/bin/env bash
 
 if [ -n "${CNB_STACK_ID:-}" ]; then
-  buildDir="$(pwd)"
-  name="Maven"
+	buildDir="$(pwd)"
+	name="Maven"
 else
-  buildDir="${1:?}"
-  name="Java"
+	buildDir="${1:?}"
+	name="Java"
 fi
 
 if [ -f "${buildDir}/pom.xml" ] ||
-    [ -f "${buildDir}/pom.atom" ] ||
-    [ -f "${buildDir}/pom.clj" ] ||
-    [ -f "${buildDir}/pom.groovy" ] ||
-    [ -f "${buildDir}/pom.rb" ] ||
-    [ -f "${buildDir}/pom.scala" ] ||
-    [ -f "${buildDir}/pom.yaml" ] ||
-    [ -f "${buildDir}/pom.yml" ] ; then
-  echo "$name"
-  exit 0
+	[ -f "${buildDir}/pom.atom" ] ||
+	[ -f "${buildDir}/pom.clj" ] ||
+	[ -f "${buildDir}/pom.groovy" ] ||
+	[ -f "${buildDir}/pom.rb" ] ||
+	[ -f "${buildDir}/pom.scala" ] ||
+	[ -f "${buildDir}/pom.yaml" ] ||
+	[ -f "${buildDir}/pom.yml" ]; then
+	echo "$name"
+	exit 0
 else
-  (>&2 echo "Could not find a pom.xml file! Please check that it exists and is committed to Git.")
-  exit 1
+	(echo >&2 "Could not find a pom.xml file! Please check that it exists and is committed to Git.")
+	exit 1
 fi
